Repository SciQLop/speasy, pull requests merged in 2025-01, with the labels that each got.

#173 Retry is server up
  speasy/core/http.py
Labels: enhancement

#177 Amda last modification date
  speasy/webservices/amda/ws.py
Labels: enhancement

#172 Add CSA GRMB parameters
  speasy/webservices/csa/__init__.py
Labels: enhancement

#174 allow to list remote files with absolute path
  speasy/core/any_files.py
  speasy/core/url_utils.py
  tests/test_file_access.py
Labels: bug, enhancement

#176 Extract more information from CDF while building the inventory
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  speasy/core/cdf/inventory_extractor.py
  speasy/webservices/cda/_inventory_builder/_cdf_masters_parser.py
  tests/test_direct_archive_downloader.py
Labels: enhancement

#170 Fixes #169, and adds functions to drop cache entries matching regex.
  pyproject.toml
  speasy/core/cache/__init__.py
  speasy/core/codecs/bundled_codecs/istp_cdf.py
  tests/test_cdaweb.py
  tests/test_common.py
Labels: bug
