Repository SciQLop/speasy, pull requests merged in 2025-02, with the labels that each got.

#195 feat: access VariableTimeAxis and VariableAxis meta
  speasy/core/data_containers.py
Labels: enhancement

#199 docs: mention julia wrapper
  README.md
  docs/index.rst
Labels: documentation

#189 Documentation improvements, Numpy support improvement and batch renaming
  Makefile
  README.ipynb
  docs/dev/index.rst
  docs/examples/index.rst
  docs/index.rst
  docs/user/amda/amda.rst
  docs/user/configuration.rst
  docs/user/data_providers.rst
  docs/user/direct_archive/direct_archive.rst
  docs/user/numpy.rst
  docs/user/scipy.rst
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  speasy/__init__.py
  speasy/core/data_containers.py
  speasy/core/http.py
  speasy/core/impex/__init__.py
  speasy/core/requests_scheduling/request_dispatch.py
  speasy/core/url_utils.py
  speasy/data_providers/__init__.py
  speasy/data_providers/amda/__init__.py
  speasy/data_providers/amda/ws.py
  speasy/data_providers/cda/__init__.py
  speasy/data_providers/cda/_direct_archive.py
  speasy/data_providers/cda/_inventory_builder/__init__.py
  speasy/data_providers/cda/_inventory_builder/_cdf_masters_parser.py
  speasy/data_providers/cda/_inventory_builder/_xml_catalogs_parser.py
  speasy/data_providers/csa/__init__.py
  speasy/data_providers/generic_archive/__init__.py
  speasy/data_providers/ssc/__init__.py
  speasy/products/variable.py
  speasy/webservices/__init__.py
  speasy/webservices/amda/__init__.py
  tests/test_cdaweb.py
  tests/test_speasy_variable.py
  tests/test_sscweb.py
Labels: documentation, enhancement

#200 Introduce a new inventory JSON/dict format that preserves more primitive types
  speasy/core/impex/__init__.py
  speasy/core/inventory/indexes.py
  speasy/core/proxy/__init__.py
  speasy/data_providers/cda/_inventory_builder/__init__.py
  speasy/data_providers/csa/__init__.py
  tests/test_inventories.py
Labels: enhancement

#201 Quick fix for leftover additional_argument instead of product_inputs
  speasy/data_providers/amda/ws.py
Labels: bug
